#!/bin/sh
sudo -v

# dot files
cp $HOME/dotfiles/.tmux.conf $HOME/
cp -R $HOME/dotfiles/.vim $HOME/
cp $HOME/dotfiles/.vimrc $HOME/
cp $HOME/dotfiles/.zshrc $HOME/

## Trackpad
defaults write -g com.apple.swipescrolldirection -bool false
# [システム環境設定 > トラックパッド > スクロールとズーム > スクロールの方向 : ナチュラル] => "OFF"


## Finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# [Finder の環境設定 > 詳細 > すべてのファイル名拡張子を表示] => "ON"

defaults write -g com.apple.keyboard.fnState -bool true
# [システム環境設定 > キーボード > キーボード > F1、F2 などのすべてのキーを標準ファンクションキーとして使用] => "ON"

defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 33 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>103</integer><integer>0</integer></array><key>type</key><string>standard</string></dict></dict>"
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 35 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>103</integer><integer>131072</integer></array><key>type</key><string>standard</string></dict></dict>"
# [システム環境設定 > キーボード > Mission Control > アプリケーションウィンドウ] = "ON"，[F11]
 
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 36 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>109</integer><integer>0</integer></array><key>type</key><string>standard</string></dict></dict>"
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 37 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>109</integer><integer>131072</integer></array><key>type</key><string>standard</string></dict></dict>"
# [システム環境設定 > キーボード > Mission Control > デスクトップを表示] = "ON"，[F10]

defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 32 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>111</integer><integer>0</integer></array><key>type</key><string>standard</string></dict></dict>"
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 34 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>111</integer><integer>131072</integer></array><key>type</key><string>standard</string></dict></dict>"
# [システム環境設定 > キーボード > Mission Control > Mission Control] = "ON"，[F12]

